// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotaCar_Rental;

#nullable disable

namespace RotaCar_Rental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241013185521_seedCarsTable")]
    partial class seedCarsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentalRateDaily")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RentalRateWeekly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fuel = "Gasoline",
                            LicensePlate = "XYZ-5678",
                            LocationID = 1,
                            Make = "Toyota",
                            Mileage = 10000,
                            Model = "Corolla",
                            RentalRateDaily = 45.5m,
                            RentalRateWeekly = 300.00m,
                            Seats = 4,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            Fuel = "Diesel",
                            LicensePlate = "ABC-1234",
                            LocationID = 1,
                            Make = "Ford",
                            Mileage = 12000,
                            Model = "Escape",
                            RentalRateDaily = 60.00m,
                            RentalRateWeekly = 400.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            Fuel = "Electric",
                            LicensePlate = "LMN-9876",
                            LocationID = 1,
                            Make = "Tesla",
                            Mileage = 8000,
                            Model = "Model 3",
                            RentalRateDaily = 90.00m,
                            RentalRateWeekly = 600.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "Sedan",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Fuel = "Hybrid",
                            LicensePlate = "JKL-3456",
                            LocationID = 1,
                            Make = "Honda",
                            Mileage = 15000,
                            Model = "CR-V",
                            RentalRateDaily = 55.00m,
                            RentalRateWeekly = 350.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "SUV",
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            Fuel = "Gasoline",
                            LicensePlate = "PQR-1122",
                            LocationID = 1,
                            Make = "BMW",
                            Mileage = 9000,
                            Model = "4 Series",
                            RentalRateDaily = 80.00m,
                            RentalRateWeekly = 500.00m,
                            Seats = 4,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "Coupe",
                            Year = 2021
                        },
                        new
                        {
                            Id = 6,
                            Fuel = "Gasoline",
                            LicensePlate = "GHJ-7789",
                            LocationID = 1,
                            Make = "Nissan",
                            Mileage = 14000,
                            Model = "Altima",
                            RentalRateDaily = 50.00m,
                            RentalRateWeekly = 330.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            Id = 7,
                            Fuel = "Gasoline",
                            LicensePlate = "ZXY-3344",
                            LocationID = 1,
                            Make = "Subaru",
                            Mileage = 5000,
                            Model = "Forester",
                            RentalRateDaily = 70.00m,
                            RentalRateWeekly = 450.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            Fuel = "Gasoline",
                            LicensePlate = "VWX-9987",
                            LocationID = 1,
                            Make = "Chevrolet",
                            Mileage = 18000,
                            Model = "Traverse",
                            RentalRateDaily = 65.00m,
                            RentalRateWeekly = 420.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "SUV",
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            Fuel = "Gasoline",
                            LicensePlate = "YUI-2345",
                            LocationID = 1,
                            Make = "Audi",
                            Mileage = 6000,
                            Model = "Q5",
                            RentalRateDaily = 85.00m,
                            RentalRateWeekly = 570.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            Id = 10,
                            Fuel = "Gasoline",
                            LicensePlate = "MNB-5567",
                            LocationID = 1,
                            Make = "Mercedes-Benz",
                            Mileage = 7000,
                            Model = "C-Class",
                            RentalRateDaily = 75.00m,
                            RentalRateWeekly = 500.00m,
                            Seats = 5,
                            Status = "Available",
                            Transmission = "Automatic",
                            Type = "Sedan",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableCar")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableCar = 25,
                            City = "Los Angeles",
                            Name = "Sunset Car Rentals",
                            Phone = "555-5678",
                            State = "California",
                            Street = "123 Sunset Blvd",
                            Zip = "90001"
                        });
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("Date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarID");

                    b.HasIndex("PaymentID");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RotaCar_Rental.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("RotaCar_Rental.Models.MaintenanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarID");

                    b.ToTable("maintenanceHistories");
                });

            modelBuilder.Entity("Car", b =>
                {
                    b.HasOne("Location", "location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("location");
                });

            modelBuilder.Entity("Rental", b =>
                {
                    b.HasOne("Car", "car")
                        .WithMany()
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment", "payment")
                        .WithMany()
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("car");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.HasOne("Car", "car")
                        .WithMany()
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("car");
                });

            modelBuilder.Entity("RotaCar_Rental.Models.Feature", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany("Features")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RotaCar_Rental.Models.MaintenanceHistory", b =>
                {
                    b.HasOne("Car", "Car")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Car", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("MaintenanceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
