//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotaCar_Rental.Resources.TR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotaCar_Rental.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Way to Rent Your Perfect Cars.
        /// </summary>
        public static string Better_Way_to_Rent_Your_Perfect_Cars {
            get {
                return ResourceManager.GetString("Better Way to Rent Your Perfect Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        public static string Book_now {
            get {
                return ResourceManager.GetString("Book now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Pickup Location.
        /// </summary>
        public static string Choose_Your_Pickup_Location {
            get {
                return ResourceManager.GetString("Choose Your Pickup Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-off date.
        /// </summary>
        public static string Drop_off_date {
            get {
                return ResourceManager.GetString("Drop-off date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-off location.
        /// </summary>
        public static string Drop_off_location {
            get {
                return ResourceManager.GetString("Drop-off location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy steps for renting a car.
        /// </summary>
        public static string Easy_steps_for_renting_a_car {
            get {
                return ResourceManager.GetString("Easy steps for renting a car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast &amp;amp; Easy Way To Rent A Car.
        /// </summary>
        public static string Fast_Easy_Way_To_Rent_A_Car {
            get {
                return ResourceManager.GetString("Fast Easy Way To Rent A Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeatured Vehicles.
        /// </summary>
        public static string Feeatured_Vehicles {
            get {
                return ResourceManager.GetString("Feeatured Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your trip.
        /// </summary>
        public static string Make_your_trip {
            get {
                return ResourceManager.GetString("Make your trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up date.
        /// </summary>
        public static string Pick_up_date {
            get {
                return ResourceManager.GetString("Pick-up date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up location.
        /// </summary>
        public static string Pick_up_location {
            get {
                return ResourceManager.GetString("Pick-up location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent A Car Now.
        /// </summary>
        public static string Rent_A_Car_Now {
            get {
                return ResourceManager.GetString("Rent A Car Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Your Perfect Car.
        /// </summary>
        public static string Reserve_Your_Perfect_Car {
            get {
                return ResourceManager.GetString("Reserve Your Perfect Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Your Rental Car.
        /// </summary>
        public static string Reserve_Your_Rental_Car {
            get {
                return ResourceManager.GetString("Reserve Your Rental Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
    }
}
