//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotaCar_Rental.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotaCar_Rental.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string All_rights_reserved {
            get {
                return ResourceManager.GetString("All rights reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Price Guarantee.
        /// </summary>
        public static string Best_Price_Guarantee {
            get {
                return ResourceManager.GetString("Best Price Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Way to Rent Your Perfect Cars.
        /// </summary>
        public static string Better_Way_to_Rent_Your_Perfect_Cars {
            get {
                return ResourceManager.GetString("Better Way to Rent Your Perfect Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book.
        /// </summary>
        public static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        public static string Book_now {
            get {
                return ResourceManager.GetString("Book now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Tips.
        /// </summary>
        public static string Booking_Tips {
            get {
                return ResourceManager.GetString("Booking Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Pickup Location.
        /// </summary>
        public static string Choose_Your_Pickup_Location {
            get {
                return ResourceManager.GetString("Choose Your Pickup Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇİFTLİKKÖY MAH.MERSİN UNIVERSITY CAMPUS AREA (CLUSTER HOUSES) TECHNOPARK SITE. NO:35 A/406 YENİŞEHİR MERSİN.
        /// </summary>
        public static string company_location {
            get {
                return ResourceManager.GetString("company location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support.
        /// </summary>
        public static string Customer_Support {
            get {
                return ResourceManager.GetString("Customer Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-off date.
        /// </summary>
        public static string Drop_off_date {
            get {
                return ResourceManager.GetString("Drop-off date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-off location.
        /// </summary>
        public static string Drop_off_location {
            get {
                return ResourceManager.GetString("Drop-off location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy steps for renting a car.
        /// </summary>
        public static string Easy_steps_for_renting_a_car {
            get {
                return ResourceManager.GetString("Easy steps for renting a car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced.
        /// </summary>
        public static string Experienced {
            get {
                return ResourceManager.GetString("Experienced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the perfect car for your trip with ease! Explore our wide range of vehicles, flexible booking options, and competitive prices. Your journey starts here!.
        /// </summary>
        public static string explanation {
            get {
                return ResourceManager.GetString("explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast &amp; Easy Way To Rent A Car.
        /// </summary>
        public static string Fast_Easy_Way_To_Rent_A_Car {
            get {
                return ResourceManager.GetString("Fast Easy Way To Rent A Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeatured Vehicles.
        /// </summary>
        public static string Feeatured_Vehicles {
            get {
                return ResourceManager.GetString("Feeatured Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are here for you with our fast and safe car rental services. Customer satisfaction is our priority..
        /// </summary>
        public static string footer_ex {
            get {
                return ResourceManager.GetString("footer ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string Happy {
            get {
                return ResourceManager.GetString("Happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a Questions?.
        /// </summary>
        public static string Have_a_Questions_ {
            get {
                return ResourceManager.GetString("Have a Questions?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string How_it_works {
            get {
                return ResourceManager.GetString("How it works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your trip.
        /// </summary>
        public static string Make_your_trip {
            get {
                return ResourceManager.GetString("Make your trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Option.
        /// </summary>
        public static string Payment_Option {
            get {
                return ResourceManager.GetString("Payment Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up date.
        /// </summary>
        public static string Pick_up_date {
            get {
                return ResourceManager.GetString("Pick-up date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up location.
        /// </summary>
        public static string Pick_up_location {
            get {
                return ResourceManager.GetString("Pick-up location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and Cookies Policy.
        /// </summary>
        public static string Privacy_and_Cookies_Policy {
            get {
                return ResourceManager.GetString("Privacy and Cookies Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent A Car Now.
        /// </summary>
        public static string Rent_A_Car_Now {
            get {
                return ResourceManager.GetString("Rent A Car Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Your Perfect Car.
        /// </summary>
        public static string Reserve_Your_Perfect_Car {
            get {
                return ResourceManager.GetString("Reserve Your Perfect Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Your Rental Car.
        /// </summary>
        public static string Reserve_Your_Rental_Car {
            get {
                return ResourceManager.GetString("Reserve Your Rental Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Best Deal.
        /// </summary>
        public static string Select_the_Best_Deal {
            get {
                return ResourceManager.GetString("Select the Best Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term and Conditions.
        /// </summary>
        public static string Term_and_Conditions {
            get {
                return ResourceManager.GetString("Term and Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
